export * from "./src/schemas/category";
export * from "./src/schemas/snippet";
export * from "./src/schemas/trash";
export * from "./src/schemas/schedule";
export * from "./src/schemas/alfa";
export * from "./src/schemas/teacher";
export * from "./src/schemas/subject";
export * from "./src/schemas/ui";
export * from "./src/schemas/user";