version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: btw-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: btw_app_2025
      POSTGRES_DB: btw_db
    ports:
      - "5434:5432"
    volumes:
      - btw_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  btw-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btw-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./apps/server/.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://root:btw_app_2025@postgres:5432/btw_db?schema=public

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Запуск от имени юзера БД
    volumes:
      - ./backups:/backups # Папка на сервере, куда будут падать дампы
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=btw_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${DB_PASSWORD:-btw_app_2025}
      # Настройки расписания (Cron). Сейчас: каждый день в 03:00 ночи
      - SCHEDULE=@daily
      # Сколько бекапов хранить (например, за последние 7 дней)
      - BACKUP_KEEP_DAYS=31

networks:
  btw-network:
    driver: bridge

volumes:
  btw_postgres_data: